services:
  at-admin:
    container_name: at-admin
    build:
      context: .
      dockerfile: deployment/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - at-network

networks:
  at-network:
    name: active-tver_at-network
    external: true
